--- 
title: "R Course"
author: "Rob Hayward"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: robhayward/R-Course2
description: "This is a practice at the R Course"
---

# Prerequisites

Placeholder



<!--chapter:end:index.Rmd-->

# Introduction {#intro}

========================================================
R is an open-source statistical programming language.  It is available from the following website: [R-Cran](http://www.r-project.org/). You should install R on you laptop.  For us it is probably best to use the [following link](http://www.stats.bris.ac.uk/R/).  You can also install [R-Studio](https://www.rstudio.com/) which is an Integrated Development Environment (IDE) for R. 

Competitors

----------------------------------------------------------
R is one of the main programmable statistical languages.  Others include:
* Stata:  Use in academic econometrics. This is not open source.
* Matlab:  Used extensively in academic finance.  It is not open-source.  There is an open-source clone called *Octave*.  It can be downloaded [here.](https://www.gnu.org/software/octave/)
* Python: Computer Language for statistical programming.  
* Julia:  New language that is faster than R
* C++:  Programming language.  Underneath R is C++ in some cases. 

Advantages of using R
------------------------------------------------------------
The main advantages of using an open-source statistical programming languages like R are:
* It can be used by anyone for no cost.  Your model will not depend on the next institution having the same software licence
* Programming language will encourage *reproducible research*

Reproducible Research
--------------------------------------------------------------
Reproducible Research means that results can be easily replicated.  This means
* Mistakes are less likely to happen than would be the case with *copy and paste*
* Mistakes can be more swiftly identified
* Changes to data or research methods are easier to make

Additional Information
---------------------------------------------------------
Some additional information on R, R-Studio and Reproducible Research 
* [LSE commentary on Reinhart and Rogoff](http://blogs.lse.ac.uk/impactofsocialsciences/2013/10/23/open-data-in-economics-the-basis-of-reproducible-research/)

<!--chapter:end:01-intro.Rmd-->


# First R

Placeholder



<!--chapter:end:02-literature.Rmd-->

